# Generated by Django 3.0.7 on 2020-06-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labman', '0002_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
