# Generated by Django 3.0.7 on 2020-06-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labman', '0003_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='author',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
