# Generated by Django 3.0.7 on 2020-06-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labman', '0004_auto_20200624_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corpus',
        ),
    ]
