# Generated by Django 3.0.7 on 2020-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labman', '0005_delete_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='priority',
            field=models.SmallIntegerField(default=1),
        ),
    ]
